In [1]:
from dgh import upper
import numpy as np

In [1]:
from grad_dgh import upper

In [ ]:
import numpy as np
np.random.seed(42)

def generate_symmetric_matrix(size, min_val=1, max_val=100):

    matrix = np.random.randint(min_val, max_val + 1, size=(size, size))
   
    symmetric_matrix = (matrix + matrix.T) / 2

    np.fill_diagonal(symmetric_matrix, 0.0)
    return symmetric_matrix



In [3]:
X = np.array([[0, 1, 10, 10],
               [0, 0, 10, 10],
               [0, 0, 0, 1],
               [0, 0, 0, 0]])
X += X.T
Y = np.array([[0, 1, 1, 10],
              [0, 0, 1, 10],
              [0, 0, 0, 10],
              [0, 0, 0, 0]])
Y += Y.T

print(upper(X,Y, iter_budget=100))

True True 4
True True 4
True True 3
True True 5
True True 3
True True 5
True False 4
True True 4
47 4 S0 1.0001
True True 4
43 4 S0 1.0001
True True 4
39 4 S0 1.0001
True True 4
35 4 S0 1.0001
True True 3
32 3 S0 1.0001
True True 5
27 5 S0 1.0001
True True 4
23 4 S0 1.0001
True True 3
20 3 S0 1.0001
True True 4
16 4 S0 1.0001
True True 3
13 3 S0 1.0001
True True 4
9 4 S0 1.0001
0.5


In [4]:
X = np.array([[0, 1, 10, 10],
               [0, 0, 10, 10],
               [0, 0, 0, 1],
               [0, 0, 0, 0]])
X += X.T
Y = np.array([[0, 1, 10, 10],
              [0, 0, 10, 10],
              [0, 0, 0, 1],
              [0, 0, 0, 0]])
Y += Y.T
print(np.array_equal(X,Y))
print(upper(X,Y, iter_budget=100))

True
True True 4
True True 2
True True 4
True True 2
True True 4
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
True True 4
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
True True 5
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
True True 3
True True 4
True True 3
True True 3
True True 2
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 

In [9]:
c_s = 1 + 10.**np.arange(-4, 9, 2)
DGH = []
for c in c_s:
    DGH.append(upper(X, Y, iter_budget=1000, c = c))

1000 1000 1.0001
1000 1000 1.01
1000 1000 2.0
1000 1000 101.0
1000 1000 10001.0
1000 1000 1000001.0
1000 1000 100000001.0


In [10]:
DGH

[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]

In [ ]:
'''
def generate_symmetric_matrix(size):
   
    matrix = np.random.uniform(-5,5, size=(size, size))
   
    symmetric_matrix = (matrix + matrix.T) / 2
   
    np.fill_diagonal(symmetric_matrix, 0.0)
    return symmetric_matrix

'''

In [6]:
X = generate_symmetric_matrix(5)
Y = X.copy()
print(np.array_equal(X,Y))

True


In [5]:
X = np.array([[ 0. , 57. , 51.5, 62.5, 31.5],
       [57. ,  0. , 93.5, 38.5, 69.5],
       [51.5, 93.5,  0. , 45.5, 41. ],
       [62.5, 38.5, 45.5,  0. , 29.5],
       [31.5, 69.5, 41. , 29.5,  0. ]])
Y = X.copy()

In [6]:
X

array([[ 0. , 57. , 51.5, 62.5, 31.5],
       [57. ,  0. , 93.5, 38.5, 69.5],
       [51.5, 93.5,  0. , 45.5, 41. ],
       [62.5, 38.5, 45.5,  0. , 29.5],
       [31.5, 69.5, 41. , 29.5,  0. ]])

In [29]:
X1 = X.copy()

In [7]:
c_s = 1 + 10.**np.arange(-4, 9, 2)
DGH = []
for c in c_s:
    print(upper(X, Y, iter_budget=10000, c = c))

True True 5
9995 5 S0 1.0001
True True 5
9990 5 S0 1.0001
True True 4
9986 4 S0 1.0001
True True 3
9983 3 S0 1.0001
True True 3
9980 3 S0 1.0001
True True 5
9980 break 1.0001
0.0
True True 5
9995 5 S0 1.01
True True 5
9990 5 S0 1.01
True True 4
9986 4 S0 1.01
True True 3
9983 3 S0 1.01
True True 3
9980 3 S0 1.01
True True 5
9980 break 1.01
0.0
True True 4
9996 4 S0 2.0
True True 3
9993 3 S0 2.0
True True 4
9989 4 S0 2.0
True True 3
9986 3 S0 2.0
True True 3
9983 3 S0 2.0
True True 5
9983 break 2.0
0.0
True True 7
9993 7 S0 101.0
True True 4
9989 4 S0 101.0
True True 5
9984 5 S0 101.0
True True 5
9979 5 S0 101.0
True True 3
9976 3 S0 101.0
True True 5
9976 break 101.0
0.0
True True 6
9994 6 S0 10001.0
True True 7
9987 7 S0 10001.0
True True 9
9978 9 S0 10001.0
True True 4
9974 4 S0 10001.0
True True 5
9969 5 S0 10001.0
True True 5
9964 5 S0 10001.0
True True 4
9960 4 S0 10001.0
True True 6
9954 6 S0 10001.0
True True 6
9948 6 S0 10001.0
True True 4
9944 4 S0 10001.0
True True 5
9939 5 S

In [38]:
c = c_s[3]
for i in ([1000,5000,10000,20000,50000]):
    print(upper(X, Y, iter_budget=i, c = c))

20.000000000000004
19.5
16.75
16.75
16.5


In [31]:
print(np.array_equal(X,X1))

True


In [1]:
import numpy as np
np.random.seed(42)

In [ ]:
def rnd_R(n, m):
    #print(n,m)
    """
    Generates random soft mapping in X🠖Y as a point in the bi-mapping polytope 𝓢.

    :param n: cardinality of X (int)
    :param m: cardinality of Y (int)
    :return: soft mapping pair S ∈ 𝓢  (2d-array)
    """
    nxn_zeros, mxm_zeros = (np.zeros((size, size)) for size in [n, m])

    F = np.random.randint(0, 2, size = (n,m))
    G = np.random.randint(0, 2, size = (m,n))
    
    R = np.block([[F, nxn_zeros], [mxm_zeros, G]])

    return R

In [7]:
np.random.choice(5, size=4, replace=True) 

array([3, 4, 2, 4])

In [2]:
import numpy as np

def random_permutation_matrix(n, m):
    """
    Генерирует случайную матрицу (n, m), где в каждой строке ровно одна 1, остальное 0.

    Аргументы:
    - n: количество строк
    - m: количество столбцов

    Возвращает:
    - R: матрица (n, m), где в каждой строке одна 1, остальное 0
    """
    R = np.zeros((n, m), dtype=int)
    col_indices = np.random.choice(m, size=n, replace=True) 
    row_indices = np.arange(n) 

    R[row_indices, col_indices] = 1 

    return R

In [ ]:
def rnd_R(n, m, nxn_zeros, mxm_zeros):
    #print(n,m)
    """
    Generates random soft mapping in X🠖Y as a point in the bi-mapping polytope 𝓢.

    :param n: cardinality of X (int)
    :param m: cardinality of Y (int)
    :param rnd: NumPy random state
    :return: soft mapping pair S ∈ 𝓢  (2d-array)
    """

    F = random_permutation_matrix(n,m)
    G = random_permutation_matrix(m,n)
    
    R = np.block([[F, nxn_zeros], [mxm_zeros, G]])

    return R

In [3]:
def dis(R, V, U, W):
 
    R_W = R @ W

    dis_R = np.abs(V - R @ U @ R.T + R_W - R_W.T).max()

    return dis_R

In [76]:
def compute_dgh(X, Y, num_tries = 1000):
    n = X.shape[0]
    m = Y.shape[0]
    #nxn_zeros, mxm_zeros = (np.zeros((size, size)) for size in [n, m])
    nxm_zeros = np.zeros((n,m))
    mxn_zeros = np.zeros((m,n))
    V = np.block([[X, nxm_zeros], [mxn_zeros, Y]])
    U = np.block([[Y, mxn_zeros], [nxm_zeros, X]])
    W = np.block([[mxn_zeros, Y], [X, nxm_zeros]])
    dis_R = 10**6
    rad_X = np.min(X.max(axis=0))
    rad_Y = np.min(Y.max(axis=0))
    nxn_zeros, mxm_zeros = (np.zeros((size, size)) for size in [n, m])
    lb = max(abs(X.max() - Y.max()), abs(rad_X - rad_Y))
    for i in range(num_tries):
        R = rnd_R(n,m, nxn_zeros, mxm_zeros)
        tmp_dis = dis(R, V, U, W)
        dis_R = min(dis_R, tmp_dis)
        if (dis_R - lb <= 0.01):
            print('s')
            return dis_R / 2
    print(R)
    return dis_R / 2

    


In [8]:
X = np.array([[0, 1, 10, 10],
               [0, 0, 10, 10],
               [0, 0, 0, 1],
               [0, 0, 0, 0]])
X += X.T
Y = np.array([[0, 1, 1, 10],
              [0, 0, 1, 10],
              [0, 0, 0, 10],
              [0, 0, 0, 0]])
Y += Y.T


In [ ]:
pip install dgh

In [5]:
import dgh

In [113]:
X = generate_symmetric_matrix(100)
Y = X.copy()
print(np.array_equal(X,Y))

True


In [104]:
X

array([[ 0. , 42. , 41. , ..., 65.5, 18.5, 45.5],
       [42. ,  0. , 37.5, ..., 63. , 39. , 45.5],
       [41. , 37.5,  0. , ..., 46.5, 19. , 54.5],
       ...,
       [65.5, 63. , 46.5, ...,  0. ,  8.5, 32. ],
       [18.5, 39. , 19. , ...,  8.5,  0. , 53. ],
       [45.5, 45.5, 54.5, ..., 32. , 53. ,  0. ]])

In [114]:
print(dgh.upper(X,Y, iter_budget=1000))

31.75


In [116]:
compute_dgh(X, Y, num_tries = 50000)

44.5

In [ ]:
def swap_units_in_blocks_optimized(R, n, m, num_swaps_F, num_swaps_G):
    """
    Меняет перестановки единиц в левом (F) и правом (G) блоках матрицы R без циклов.

    Параметры:
    - R: матрица (n + m) x (n + m), состоящая из блоков F (n x m) и G (m x n).
    - n: количество строк в блоке F.
    - m: количество строк в блоке G.
    - num_swaps_F: количество строк в блоке F, в которых нужно изменить перестановки единиц.
    - num_swaps_G: количество строк в блоке G, в которых нужно изменить перестановки единиц.

    Возвращает:
    - Новую матрицу R с изменёнными перестановками единиц.
    """
    R_new = R.copy()

    F = R_new[:n, :m]

    G = R_new[n:, m:]

    if num_swaps_F > 0:
    
        rows_F = np.random.choice(n, size=num_swaps_F, replace=False)

        current_units_F = np.argmax(F[rows_F], axis=1)

        new_units_F = np.array([np.random.choice([i for i in range(m) if i != current_unit]) 
                                for current_unit in current_units_F])

        F[rows_F, current_units_F] = 0
        F[rows_F, new_units_F] = 1

    if num_swaps_G > 0:
       
        rows_G = np.random.choice(m, size=num_swaps_G, replace=False)

        current_units_G = np.argmax(G[rows_G], axis=1)

        new_units_G = np.array([np.random.choice([i for i in range(n) if i != current_unit]) 
                                for current_unit in current_units_G])

        G[rows_G, current_units_G] = 0
        G[rows_G, new_units_G] = 1

    R_new[:n, :m] = F
    R_new[n:, m:] = G

    return R_new

In [104]:
n = 3
m = 4
nxn_zeros, mxm_zeros = (np.zeros((size, size)) for size in [n, m])

R = rnd_R(n,m, nxn_zeros, mxm_zeros)

In [105]:
R

array([[1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [106]:
swap_units_in_blocks_optimized(R, n, m, 2, 2)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [36]:
np.random.rand()

0.230893825622149

In [ ]:
def make_fire(U,V,W,n,m,nxn_zeros,mxm_zeros, max_iter = 100000):
    T_0 = 5.6
    T = T_0
    #alpha = 0.99
    break_count = 0
    R = rnd_R(n,m, nxn_zeros, mxm_zeros)
    cur_energy = dis(R,V,U,W)
    for i in range(max_iter):
        #T *= alpha
        T = T_0 / (i+1)
        R_new = swap_units_in_blocks_optimized(R,n,m,1,1)
        candidate_energy = dis(R_new, V, U, W)
        delta_energy = candidate_energy - cur_energy
        if (delta_energy < 0 or np.random.rand() < np.exp(-delta_energy / T)):
            R = R_new
            cur_energy = candidate_energy
        if (T < 0.00001):
            break_count = 1
            break
    return cur_energy, break_count



In [94]:
def compute_dgh_fire(X, Y, num_tries = 100):
    break_count = 0
    n = X.shape[0]
    m = Y.shape[0]
    nxm_zeros = np.zeros((n,m))
    mxn_zeros = np.zeros((m,n))
    V = np.block([[X, nxm_zeros], [mxn_zeros, Y]])
    U = np.block([[Y, mxn_zeros], [nxm_zeros, X]])
    W = np.block([[mxn_zeros, Y], [X, nxm_zeros]])
    dis_R = 10**6
    rad_X = np.min(X.max(axis=0))
    rad_Y = np.min(Y.max(axis=0))
    nxn_zeros, mxm_zeros = (np.zeros((size, size)) for size in [n, m])
    lb = max(abs(X.max() - Y.max()), abs(rad_X - rad_Y))

    for i in range(num_tries):
        tmp_dis, count = make_fire(U,V,W,n,m,nxn_zeros,mxm_zeros)
        break_count += count
        dis_R = min(dis_R, tmp_dis)
        if (dis_R - lb <= 0.01):
            print('s')
            print(break_count)
            return dis_R / 2
    print(break_count)
    return dis_R / 2


In [53]:
X = generate_symmetric_matrix(5)
Y = X.copy()
print(np.array_equal(X,Y))

True


In [54]:
print(dgh.upper(X,Y, iter_budget=100))

9.000000000000002


In [62]:
compute_dgh_fire(X,Y)

break
s


0.0

In [108]:
X = generate_symmetric_matrix(8)
Y = X.copy()
print(np.array_equal(X,Y))

True


In [109]:
print(dgh.upper(X,Y, iter_budget=100))

15.500000000000002


In [113]:
compute_dgh_fire(X,Y, num_tries=500)

500


15.0

In [120]:
compute_dgh_fire(X,Y, num_tries=50)

s
0


0.0

In [6]:
X = generate_symmetric_matrix(5)
Y = X.copy()
print(np.array_equal(X,Y))

True


In [7]:
dgh.upper(X,Y)

0.0

In [ ]:
import numpy as np

def generate_solution(n, m):
  
    p1 = np.random.choice(m, size = n)  # Индексы для первого блока
    p2 = np.random.choice(n, size = m)  # Индексы для второго блока
    return p1, p2


In [58]:
import numpy as np

def build_matrix(p1, p2, nxn_zeros, mxm_zeros):
    """
    Generates random soft mapping in X🠖Y as a point in the bi-mapping polytope 𝓢.

    :param n: cardinality of X (int)
    :param m: cardinality of Y (int)
    :param rnd: NumPy random state
    :return: soft mapping pair S ∈ 𝓢  (2d-array)
    """
    F = np.zeros((n, m), dtype=int)
    row_indices = np.arange(n)
    #print(F.shape, row_indices, p2)
    F[row_indices, p1] = 1 

    G = np.zeros((m, n), dtype=int)
    row_indices = np.arange(m)
    #print(G.shape, row_indices, p1)
    G[row_indices, p2] = 1 
    
    R = np.block([[F, nxn_zeros], [mxm_zeros, G]])

    return R



In [65]:
n, m = 3,3
nxn_zeros, mxm_zeros = (np.zeros((size, size)) for size in [n, m])

In [66]:
print(p1,p2)

[0 0 2] [0 0 0 2]


In [67]:
p1, p2 = generate_solution(n,m)
build_matrix(p1,p2, nxn_zeros, mxm_zeros)

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.]])

In [91]:
import numpy as np

def dis(R, V, U, W):
 
    R_W = R @ W

    dis_R = np.abs(V - R @ U @ R.T + R_W - R_W.T).max()

    return dis_R

def build_matrix(p1, p2, nxn_zeros, mxm_zeros):

    n, m = len(p1), len(p2)
    
    F = np.zeros((n, m), dtype=int)
    row_indices = np.arange(n)
    F[row_indices, p1] = 1 

    G = np.zeros((m, n), dtype=int)
    row_indices = np.arange(m)
    G[row_indices, p2] = 1 
    
    R = np.block([[F, nxn_zeros], [mxm_zeros, G]])

    return R

class AntColonyMatrix:
    def __init__(self, X, Y, alpha=1, rho=0.1, Q=1):
        n = X.shape[0]
        m = Y.shape[1]
        nxm_zeros = np.zeros((n,m))
        mxn_zeros = np.zeros((m,n))
        self.V = np.block([[X, nxm_zeros], [mxn_zeros, Y]])
        self.U = np.block([[Y, mxn_zeros], [nxm_zeros, X]])
        self.W = np.block([[mxn_zeros, Y], [X, nxm_zeros]])
        self.nxn_zeros, self.mxm_zeros = (np.zeros((size, size)) for size in [n, m])
        self.n = n
        self.m = m
        self.alpha = alpha
        self.rho = rho
        self.Q = Q
        self.tau_left = np.ones((n, m)) 
        self.tau_right = np.ones((m, n))
        rad_X = np.min(X.max(axis=0))       
        rad_Y = np.min(Y.max(axis=0))
        self.lb = max(abs(X.max() - Y.max()), abs(rad_X - rad_Y))

    def select_column(self, tau_row):
        """Выбирает столбец на основе вероятностей"""
        probs = tau_row ** self.alpha
        probs /= probs.sum()
        return np.random.choice(len(probs), p=probs)

    def construct_solution(self):
        """Создает одну матрицу (2 перестановки) на основе вероятностей"""
        p1 = [self.select_column(self.tau_left[i]) for i in range(self.n)]
        p2 = [self.select_column(self.tau_right[i]) for i in range(self.m)]
        return np.array(p1), np.array(p2)

    def update_pheromones(self, best_solutions, best_fitnesses):
        self.tau_left *= (1 - self.rho)
        self.tau_right *= (1 - self.rho)
        for (p1, p2), fitness in zip(best_solutions, best_fitnesses):
            for i in range(self.n):
                self.tau_left[i, p1[i]] += self.Q / fitness
            for i in range (self.m):
                self.tau_right[i, p2[i]] += self.Q / fitness

    def run(self, num_iterations=100, num_ants=10, num_best=3):
        best_solution = None
        best_fitness = float('inf')
    

        for iteration in range(num_iterations):
            solutions = [self.construct_solution() for _ in range(num_ants)]
            fitnesses = [dis(build_matrix(s[0],s[1],self.nxn_zeros, self.mxm_zeros), self.V, self.U, self.W) for s in solutions]

            sorted_idx = np.argsort(fitnesses)
            best_solutions = [solutions[i] for i in sorted_idx[:num_best]]
            best_fitnesses = [fitnesses[i] for i in sorted_idx[:num_best]]

            if abs(best_fitnesses[0] - self.lb) <= 1e-1:
                print("GAP")
                return best_fitnesses[0]

            self.update_pheromones(best_solutions, best_fitnesses)

            if best_fitnesses[0] < best_fitness:
                best_solution = best_solutions[0]
                best_fitness = best_fitnesses[0]

            print(f"Итерация {iteration+1}: лучший fitness = {best_fitness}")
            

        return best_fitness


In [ ]:
import numpy as np
np.random.seed(42)

def generate_symmetric_matrix(size, min_val=1, max_val=100):
    
    matrix = np.random.randint(min_val, max_val + 1, size=(size, size))
    symmetric_matrix = (matrix + matrix.T) / 2
    np.fill_diagonal(symmetric_matrix, 0.0)
    return symmetric_matrix


In [26]:
X = generate_symmetric_matrix(3)
Y = X.copy()

In [92]:
ants = AntColonyMatrix(X,Y)

In [ ]:
z = ants.run(num_best=5)

Итерация 1: лучший fitness = 47.0
Итерация 2: лучший fitness = 47.0
Итерация 3: лучший fitness = 47.0
Итерация 4: лучший fitness = 47.0
Итерация 5: лучший fitness = 47.0
Итерация 6: лучший fitness = 47.0
Итерация 7: лучший fitness = 47.0
Итерация 8: лучший fitness = 47.0
Итерация 9: лучший fitness = 47.0
Итерация 10: лучший fitness = 47.0
Итерация 11: лучший fitness = 30.5
GAP


In [94]:
z

0.0

In [95]:
X = generate_symmetric_matrix(3)
Y = X.copy()

In [96]:
ants = AntColonyMatrix(X,Y)

In [97]:
ants.run(num_best=5)

Итерация 1: лучший fitness = 45.5
Итерация 2: лучший fitness = 24.5
Итерация 3: лучший fitness = 24.5
Итерация 4: лучший fitness = 24.5
Итерация 5: лучший fitness = 24.5
Итерация 6: лучший fitness = 24.5
Итерация 7: лучший fitness = 24.5
Итерация 8: лучший fitness = 24.5
Итерация 9: лучший fitness = 24.5
Итерация 10: лучший fitness = 24.5
Итерация 11: лучший fitness = 24.5
Итерация 12: лучший fitness = 24.5
Итерация 13: лучший fitness = 24.5
Итерация 14: лучший fitness = 24.5
Итерация 15: лучший fitness = 24.5
Итерация 16: лучший fitness = 24.5
Итерация 17: лучший fitness = 24.5
Итерация 18: лучший fitness = 24.5
Итерация 19: лучший fitness = 24.5
Итерация 20: лучший fitness = 24.5
Итерация 21: лучший fitness = 24.5
Итерация 22: лучший fitness = 24.5
Итерация 23: лучший fitness = 24.5
Итерация 24: лучший fitness = 24.5
Итерация 25: лучший fitness = 24.5
Итерация 26: лучший fitness = 24.5
Итерация 27: лучший fitness = 24.5
Итерация 28: лучший fitness = 24.5
Итерация 29: лучший fitness =

0.0

In [98]:
X = generate_symmetric_matrix(4)
Y = X.copy()
ants = AntColonyMatrix(X,Y)
ants.run(num_best=5)

Итерация 1: лучший fitness = 75.0
Итерация 2: лучший fitness = 75.0
Итерация 3: лучший fitness = 73.5
Итерация 4: лучший fitness = 57.0
Итерация 5: лучший fitness = 57.0
Итерация 6: лучший fitness = 43.0
Итерация 7: лучший fitness = 43.0
Итерация 8: лучший fitness = 43.0
Итерация 9: лучший fitness = 43.0
Итерация 10: лучший fitness = 43.0
Итерация 11: лучший fitness = 43.0
Итерация 12: лучший fitness = 43.0
Итерация 13: лучший fitness = 43.0
Итерация 14: лучший fitness = 43.0
Итерация 15: лучший fitness = 43.0
Итерация 16: лучший fitness = 43.0
Итерация 17: лучший fitness = 43.0
Итерация 18: лучший fitness = 43.0
Итерация 19: лучший fitness = 43.0
Итерация 20: лучший fitness = 43.0
Итерация 21: лучший fitness = 43.0
Итерация 22: лучший fitness = 43.0
Итерация 23: лучший fitness = 43.0
Итерация 24: лучший fitness = 43.0
Итерация 25: лучший fitness = 43.0
Итерация 26: лучший fitness = 43.0
Итерация 27: лучший fitness = 43.0
Итерация 28: лучший fitness = 37.0
Итерация 29: лучший fitness =

0.0

In [105]:
X = generate_symmetric_matrix(5)
Y = X.copy()
ants = AntColonyMatrix(X,Y)
ants.run(num_best=5, num_iterations=500, num_ants=20)

Итерация 1: лучший fitness = 71.0
Итерация 2: лучший fitness = 71.0
Итерация 3: лучший fitness = 71.0
Итерация 4: лучший fitness = 71.0
Итерация 5: лучший fitness = 71.0
Итерация 6: лучший fitness = 71.0
Итерация 7: лучший fitness = 71.0
Итерация 8: лучший fitness = 71.0
Итерация 9: лучший fitness = 61.0
Итерация 10: лучший fitness = 61.0
Итерация 11: лучший fitness = 61.0
Итерация 12: лучший fitness = 61.0
Итерация 13: лучший fitness = 61.0
Итерация 14: лучший fitness = 61.0
Итерация 15: лучший fitness = 61.0
Итерация 16: лучший fitness = 61.0
Итерация 17: лучший fitness = 61.0
Итерация 18: лучший fitness = 61.0
Итерация 19: лучший fitness = 61.0
Итерация 20: лучший fitness = 61.0
Итерация 21: лучший fitness = 61.0
Итерация 22: лучший fitness = 61.0
Итерация 23: лучший fitness = 61.0
Итерация 24: лучший fitness = 60.0
Итерация 25: лучший fitness = 60.0
Итерация 26: лучший fitness = 60.0
Итерация 27: лучший fitness = 60.0
Итерация 28: лучший fitness = 60.0
Итерация 29: лучший fitness =

48.0

In [ ]:
X = generate_symmetric_matrix(5)
Y = X.copy()
ants = AntColonyMatrix(X,Y)
ants.run(num_best=10, num_iterations=50, num_ants=100)

Итерация 1: лучший fitness = 61.0
Итерация 2: лучший fitness = 61.0
Итерация 3: лучший fitness = 61.0
Итерация 4: лучший fitness = 48.0
Итерация 5: лучший fitness = 48.0
Итерация 6: лучший fitness = 48.0
Итерация 7: лучший fitness = 48.0
Итерация 8: лучший fitness = 48.0
Итерация 9: лучший fitness = 48.0
Итерация 10: лучший fitness = 48.0
Итерация 11: лучший fitness = 48.0
Итерация 12: лучший fitness = 48.0
Итерация 13: лучший fitness = 42.0
Итерация 14: лучший fitness = 42.0
Итерация 15: лучший fitness = 42.0
Итерация 16: лучший fitness = 42.0
Итерация 17: лучший fitness = 42.0
Итерация 18: лучший fitness = 42.0
Итерация 19: лучший fitness = 42.0
Итерация 20: лучший fitness = 42.0
Итерация 21: лучший fitness = 42.0
Итерация 22: лучший fitness = 42.0
Итерация 23: лучший fitness = 42.0
Итерация 24: лучший fitness = 42.0
Итерация 25: лучший fitness = 42.0
Итерация 26: лучший fitness = 42.0
Итерация 27: лучший fitness = 42.0
Итерация 28: лучший fitness = 42.0
Итерация 29: лучший fitness =

0.0

In [112]:
ants = AntColonyMatrix(X,Y)
ants.run(num_best=10, num_iterations=100, num_ants=100)

Итерация 1: лучший fitness = 42.0
Итерация 2: лучший fitness = 42.0
Итерация 3: лучший fitness = 42.0
Итерация 4: лучший fitness = 42.0
Итерация 5: лучший fitness = 42.0
Итерация 6: лучший fitness = 42.0
Итерация 7: лучший fitness = 42.0
Итерация 8: лучший fitness = 42.0
Итерация 9: лучший fitness = 42.0
Итерация 10: лучший fitness = 42.0
Итерация 11: лучший fitness = 42.0
Итерация 12: лучший fitness = 42.0
Итерация 13: лучший fitness = 42.0
Итерация 14: лучший fitness = 42.0
Итерация 15: лучший fitness = 42.0
Итерация 16: лучший fitness = 42.0
Итерация 17: лучший fitness = 42.0
Итерация 18: лучший fitness = 42.0
Итерация 19: лучший fitness = 42.0
Итерация 20: лучший fitness = 42.0
Итерация 21: лучший fitness = 42.0
Итерация 22: лучший fitness = 42.0
Итерация 23: лучший fitness = 42.0
Итерация 24: лучший fitness = 42.0
Итерация 25: лучший fitness = 42.0
Итерация 26: лучший fitness = 22.0
Итерация 27: лучший fitness = 22.0
Итерация 28: лучший fitness = 22.0
Итерация 29: лучший fitness =

0.0

In [113]:
X = generate_symmetric_matrix(10)
Y = X.copy()

In [118]:
ants = AntColonyMatrix(X,Y)
ants.run(num_best=20, num_iterations=200, num_ants=500)

Итерация 1: лучший fitness = 70.5
Итерация 2: лучший fitness = 70.5
Итерация 3: лучший fitness = 70.5
Итерация 4: лучший fitness = 64.5
Итерация 5: лучший fitness = 64.5
Итерация 6: лучший fitness = 64.5
Итерация 7: лучший fitness = 64.5
Итерация 8: лучший fitness = 64.5
Итерация 9: лучший fitness = 64.5
Итерация 10: лучший fitness = 64.5
Итерация 11: лучший fitness = 64.5
Итерация 12: лучший fitness = 64.5
Итерация 13: лучший fitness = 64.5
Итерация 14: лучший fitness = 64.5
Итерация 15: лучший fitness = 64.5
Итерация 16: лучший fitness = 64.5
Итерация 17: лучший fitness = 64.5
Итерация 18: лучший fitness = 64.5
Итерация 19: лучший fitness = 64.5
Итерация 20: лучший fitness = 64.5
Итерация 21: лучший fitness = 64.5
Итерация 22: лучший fitness = 64.5
Итерация 23: лучший fitness = 64.5
Итерация 24: лучший fitness = 64.5
Итерация 25: лучший fitness = 64.5
Итерация 26: лучший fitness = 64.5
Итерация 27: лучший fitness = 64.5
Итерация 28: лучший fitness = 64.5
Итерация 29: лучший fitness =

48.5

In [120]:
ants = AntColonyMatrix(X,Y)
ants.run(num_best=20, num_iterations=200, num_ants=1000)

Итерация 1: лучший fitness = 71.0
Итерация 2: лучший fitness = 64.0
Итерация 3: лучший fitness = 64.0
Итерация 4: лучший fitness = 64.0
Итерация 5: лучший fitness = 64.0
Итерация 6: лучший fitness = 64.0
Итерация 7: лучший fitness = 64.0
Итерация 8: лучший fitness = 64.0
Итерация 9: лучший fitness = 64.0
Итерация 10: лучший fitness = 64.0
Итерация 11: лучший fitness = 62.5
Итерация 12: лучший fitness = 62.5
Итерация 13: лучший fitness = 62.5
Итерация 14: лучший fitness = 62.5
Итерация 15: лучший fitness = 62.5
Итерация 16: лучший fitness = 62.5
Итерация 17: лучший fitness = 62.5
Итерация 18: лучший fitness = 62.5
Итерация 19: лучший fitness = 62.5
Итерация 20: лучший fitness = 62.5
Итерация 21: лучший fitness = 62.5
Итерация 22: лучший fitness = 62.5
Итерация 23: лучший fitness = 62.5
Итерация 24: лучший fitness = 62.5
Итерация 25: лучший fitness = 62.5
Итерация 26: лучший fitness = 62.5
Итерация 27: лучший fitness = 62.5
Итерация 28: лучший fitness = 62.5
Итерация 29: лучший fitness =

34.5